cpudet-clean.o: cpudet-clean.c cpuid.h
	sudo gcc -m32 -O -fstrength-reduce -fomit-frame-pointer -finline-functions -fno-builtin -c cpudet-clean.c -o ../../cpudet-clean.o -fno-exceptions -ffreestanding
